stages:
  - test
  - build
  - release
  - deploy

# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
services:
  #  - mongodb:latest
  - firebase:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

code-testing:
  image: node:latest
  stage: test
  before_script:
    - echo "Run tests, run!"
  script:
    - npm install
    - npm test
  artifacts:
    paths:
      - coverage/
